=== TUW-GEO/ascat/src/ascat/read_native/formats/eps.dtd
<!--
File: eps.dtd
Purpose: Format of Eugene EPS protocol formats descriptions
$Log: eps.dtd,v $
Revision 1.1  2003/02/28 10:49:19  melson
Initial revision


Copyright (c) Eumetsat 2003, 2004
-->


<!ELEMENT format ((version-control|brief-description|full-description|file-extensions|geolocation|image|parameters|protocol|product)*) >

<!ELEMENT version-control ((format-version|pfs-version)*) >
<!ELEMENT format-version ((major|minor|baseline)*) >
<!ELEMENT pfs-version ((major|minor)*) >
<!ELEMENT baseline (#PCDATA) >
<!ELEMENT major (#PCDATA) >
<!ELEMENT minor (#PCDATA) >

<!ELEMENT brief-description (#PCDATA) >
<!ELEMENT full-description (#PCDATA) >

<!ELEMENT file-extensions ((glob)*) >
<!ELEMENT glob (#PCDATA) >

<!ELEMENT geolocation (#PCDATA|name|description|latitude|longitude)* >
<!ELEMENT latitude (#PCDATA) >
<!ELEMENT longitude (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT label (#PCDATA) >

<!ELEMENT image ((parameter|name|description|source|geolocation)*) >
<!ELEMENT source (#PCDATA) >

<!ELEMENT parameters ((parameter)*) >
<!ELEMENT parameter (#PCDATA|label|name)* >

<!ELEMENT protocol (#PCDATA) >

<!ELEMENT product ((mphr|sphr|geadr|giadr|veadr|viadr|mdr)*) >
<!ELEMENT mphr ((section|field|array|delimiter)*) >
<!ELEMENT sphr ((section|field|array|delimiter)*) >
<!ELEMENT geadr EMPTY >
<!ELEMENT giadr ((section|field|array|delimiter)*) >
<!ELEMENT veadr EMPTY >
<!ELEMENT viadr ((section|field|array|delimiter)*) >
<!ELEMENT mdr ((section|field|array|delimiter|if)*) >

<!ELEMENT section ((section|field|array|delimiter)*) >
<!ELEMENT if ((field|section|array|delimiter)*) >
<!ELEMENT array ((field|section|array|delimiter|bit)*) >
<!ELEMENT field ((item|bit|bits|array|delimiter)*) >
<!ELEMENT delimiter EMPTY >
<!ELEMENT item EMPTY >
<!ELEMENT bit EMPTY >
<!ELEMENT bits EMPTY >

<!ATTLIST format >
<!ATTLIST version-control >
<!ATTLIST format-version >
<!ATTLIST pfs-version >
<!ATTLIST baseline >
<!ATTLIST major >
<!ATTLIST minor >
<!ATTLIST brief-description >
<!ATTLIST full-description >
<!ATTLIST file-extensions >
<!ATTLIST glob >
<!ATTLIST parameters >
<!ATTLIST parameter name CDATA #IMPLIED 
		    value CDATA #IMPLIED
		    description CDATA #IMPLIED>

<!ATTLIST protocol >

<!ATTLIST product name CDATA #IMPLIED
                  version CDATA #IMPLIED>

<!ATTLIST mphr version CDATA #IMPLIED
               block-size CDATA #IMPLIED
               name CDATA #IMPLIED
               subclass CDATA #IMPLIED
               description CDATA #IMPLIED>

<!ATTLIST sphr name CDATA #IMPLIED
               version CDATA #IMPLIED
               description CDATA #IMPLIED
               instrument CDATA #IMPLIED
               subclass CDATA #IMPLIED
               block-size CDATA #IMPLIED>

<!ATTLIST geadr name CDATA #IMPLIED
                version CDATA #IMPLIED
                subclass CDATA #IMPLIED
                instrument CDATA #IMPLIED
                description CDATA #IMPLIED
                block-size CDATA #IMPLIED>

<!ATTLIST giadr name CDATA #IMPLIED
                subclass CDATA #IMPLIED
                version CDATA #IMPLIED
                instrument CDATA #IMPLIED
                description CDATA #IMPLIED
                block-size CDATA #IMPLIED>

<!ATTLIST veadr name CDATA #IMPLIED
                version CDATA #IMPLIED
                subclass CDATA #IMPLIED
                block-size CDATA #IMPLIED
                instrument CDATA #IMPLIED
                description CDATA #IMPLIED>

<!ATTLIST viadr name CDATA #IMPLIED
                subclass CDATA #IMPLIED
                version CDATA #IMPLIED
                instrument CDATA #IMPLIED
                description CDATA #IMPLIED
                block-size CDATA #IMPLIED
                class CDATA #IMPLIED>

<!ATTLIST mdr name CDATA #IMPLIED
              subclass CDATA #IMPLIED
              version CDATA #IMPLIED
              instrument CDATA #IMPLIED
              description CDATA #IMPLIED
              block-size CDATA #IMPLIED>

<!ATTLIST section name CDATA #IMPLIED
                  description CDATA #IMPLIED
                  type CDATA #IMPLIED
                  block-size CDATA #IMPLIED>

<!ATTLIST delimiter name CDATA #IMPLIED>

<!ATTLIST field name CDATA #IMPLIED
                type CDATA #REQUIRED
                length CDATA #IMPLIED
                description CDATA #IMPLIED
                units CDATA #IMPLIED
                scaling-factor CDATA #IMPLIED
                default CDATA #IMPLIED
		variable CDATA #IMPLIED
                invalid CDATA #IMPLIED>

<!ATTLIST if source CDATA #REQUIRED
             condition CDATA #REQUIRED
	     value CDATA #REQUIRED>

<!ATTLIST array name CDATA #IMPLIED
                labels CDATA #IMPLIED
                label CDATA #IMPLIED
                length CDATA #REQUIRED
		type CDATA #IMPLIED>

<!ATTLIST item value CDATA #IMPLIED
               name CDATA #IMPLIED
               description CDATA #IMPLIED>

<!ATTLIST bit name CDATA #IMPLIED
              length CDATA #IMPLIED
              description CDATA #IMPLIED
              default CDATA #IMPLIED>

<!ATTLIST bits name CDATA #IMPLIED
              length CDATA #IMPLIED
              description CDATA #IMPLIED>

=== TUW-GEO/ascat/src/ascat/formats/eps_ascatl1bszo_7.0.xml
<?xml version="1.0"?>
<!DOCTYPE format SYSTEM "eps.dtd">
<?xml-stylesheet type="text/xsl" href="eps.xsl"?>


<!--
    File: eps_ascatl1bszo_7.0.xml

    Copyright (c) 2004-2008 Eumetsat

    This file is part of the EPSXML format specification generated
    automatically using pfs2xml.

    This XML description is distributed under the GPL license; you can
    redistribute it and/or modify it under the terms of the GNU General
    Public License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This XML description is distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the pfs2xml package; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
-->


<format>


<version-control>
    <format-version>
        <major>5</major><minor>0</minor>
	<baseline>postnov05</baseline>
    </format-version>
    <format-version>
        <major>11</major><minor>0</minor>
	<baseline>launch</baseline>
    </format-version>
    <pfs-version>
        <major>7</major><minor>0</minor>
    </pfs-version>
</version-control>


<brief-description>EPS ASCAT Level SZO_1B Format</brief-description>


<full-description>
    This ASCAT SZO_1B description was generated using the ASCAT PFS Excel document Issue 6 Revision 6 (eps_ascatl1_6.6_names_masks.xls) and pfs2xml version 3.3
</full-description>


<file-extensions>
    <glob>ASCA_SZO_1B_*Z*</glob>
</file-extensions>


<geolocation>
    <name>Geolocation</name>
    <description>ASCAT SZO L1B 50km Geolocation Coverage (Latitude, Longitude)</description>
    <latitude>mdr-1b-50km[].LATITUDE[]</latitude>
    <longitude>mdr-1b-50km[].LONGITUDE[]</longitude>
</geolocation>


<image>
    <name>SIGMA0_TRIP FORE</name>
    <description>ASCAT SZO L1B 50km SIGMA0_TRIP FORE</description>
    <source>mdr-1b-50km[].SIGMA0_TRIP[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>SIGMA0_TRIP MID</name>
    <description>ASCAT SZO L1B 50km SIGMA0_TRIP MID</description>
    <source>mdr-1b-50km[].SIGMA0_TRIP[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>SIGMA0_TRIP AFT</name>
    <description>ASCAT SZO L1B 50km SIGMA0_TRIP AFT</description>
    <source>mdr-1b-50km[].SIGMA0_TRIP[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_KP FORE</name>
    <description>ASCAT SZO L1B 50km KP Estimate Flag FORE</description>
    <source>mdr-1b-50km[].F_KP[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_KP MID</name>
    <description>ASCAT SZO L1B 50km KP Estimate Flag MID</description>
    <source>mdr-1b-50km[].F_KP[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_KP AFT</name>
    <description>ASCAT SZO L1B 50km KP Estimate Flag AFT</description>
    <source>mdr-1b-50km[].F_KP[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_USABLE FORE</name>
    <description>ASCAT SZO L1B 50km usability of averaged values FORE</description>
    <source>mdr-1b-50km[].F_USABLE[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_USABLE MID</name>
    <description>ASCAT SZO L1B 50km usability of averaged values MID</description>
    <source>mdr-1b-50km[].F_USABLE[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_USABLE AFT</name>
    <description>ASCAT SZO L1B 50km usability of averaged values AFT</description>
    <source>mdr-1b-50km[].F_USABLE[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_F FORE</name>
    <description>ASCAT SZO L1B 50km synthetic data used flag FORE</description>
    <source>mdr-1b-50km[].F_F[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_F MID</name>
    <description>ASCAT SZO L1B 50km synthetic data used flag MID</description>
    <source>mdr-1b-50km[].F_F[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_F AFT</name>
    <description>ASCAT SZO L1B 50km synthetic data used flag AFT</description>
    <source>mdr-1b-50km[].F_F[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_V FORE</name>
    <description>ASCAT SZO L1B 50km quality of synthetic data use flag FORE</description>
    <source>mdr-1b-50km[].F_V[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_V MID</name>
    <description>ASCAT SZO L1B 50km quality of synthetic data use flag MID</description>
    <source>mdr-1b-50km[].F_V[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_V AFT</name>
    <description>ASCAT SZO L1B 50km quality of synthetic data use flag AFT</description>
    <source>mdr-1b-50km[].F_V[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_OA FORE</name>
    <description>ASCAT SZO L1B 50km orbit attitdue quality flag FORE</description>
    <source>mdr-1b-50km[].F_OA[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_OA MID</name>
    <description>ASCAT SZO L1B 50km orbit attitdue quality flag MID</description>
    <source>mdr-1b-50km[].F_OA[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_OA AFT</name>
    <description>ASCAT SZO L1B 50km orbit attitdue quality flag AFT</description>
    <source>mdr-1b-50km[].F_OA[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_SA FORE</name>
    <description>ASCAT SZO L1B 50km solar array reflection contamination flag FORE</description>
    <source>mdr-1b-50km[].F_SA[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_SA MID</name>
    <description>ASCAT SZO L1B 50km solar array reflection contamination flag MID</description>
    <source>mdr-1b-50km[].F_SA[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_SA AFT</name>
    <description>ASCAT SZO L1B 50km solar array reflection contamination flag AFT</description>
    <source>mdr-1b-50km[].F_SA[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_TEL FORE</name>
    <description>ASCAT SZO L1B 50km telemtry quality flag FORE</description>
    <source>mdr-1b-50km[].F_TEL[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_TEL MID</name>
    <description>ASCAT SZO L1B 50km telemtry quality flag MID</description>
    <source>mdr-1b-50km[].F_TEL[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_TEL AFT</name>
    <description>ASCAT SZO L1B 50km telemtry quality flag AFT</description>
    <source>mdr-1b-50km[].F_TEL[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_EXT_FIL FORE</name>
    <description>ASCAT SZO L1B 50km presence of extrapolated reference functions flag FORE</description>
    <source>mdr-1b-50km[].F_EXT_FIL[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_EXT_FIL MID</name>
    <description>ASCAT SZO L1B 50km presence of extrapolated reference functions flag MID</description>
    <source>mdr-1b-50km[].F_EXT_FIL[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_EXT_FIL AFT</name>
    <description>ASCAT SZO L1B 50km presence of extrapolated reference functions flag AFT</description>
    <source>mdr-1b-50km[].F_EXT_FIL[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_LAND FORE</name>
    <description>ASCAT SZO L1B 50km use of measurements over land flag FORE</description>
    <source>mdr-1b-50km[].F_LAND[][0]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_LAND MID</name>
    <description>ASCAT SZO L1B 50km use of measurements over land flag MID</description>
    <source>mdr-1b-50km[].F_LAND[][1]</source>
    <geolocation>Geolocation</geolocation>
</image>


<image>
    <name>F_LAND AFT</name>
    <description>ASCAT SZO L1B 50km use of measurements over land flag AFT</description>
    <source>mdr-1b-50km[].F_LAND[][2]</source>
    <geolocation>Geolocation</geolocation>
</image>


<protocol>eps-product</protocol>

<product name="ASCAT-SZO_1B" version="Issue 6 Revision 6">

    <mphr name="mphr" version="2" description="Main Product Header Record ">
        <delimiter name="Product Details"/>
        <field name="PRODUCT_NAME" type="string" length="67" description="Complete name of the product"/>
        <field name="PARENT_PRODUCT_NAME_1" type="string" length="67" description="Name of the parent product from which this product has been produced. For Level 0 products, this field is filled with lower case x's."/>
        <field name="PARENT_PRODUCT_NAME_2" type="string" length="67" description="Name of the parent product from which this product has been produced. For Level 0 products or products for which this is not appropriate, this field is filled with lower case x's."/>
        <field name="PARENT_PRODUCT_NAME_3" type="string" length="67" description="Name of the parent product from which this product has been produced. For Level 0 products or products for which this is not appropriate, this field is filled with lower case x's."/>
        <field name="PARENT_PRODUCT_NAME_4" type="string" length="67" description="Name of the parent product from which this product has been produced. For Level 0 products or products for which this is not appropriate, this field is filled with lower case x's."/>
